### ISSUE TITLE
Api version and/or network error

### ISSUE THREAD

**Issue by chikoi** [viest/PHP-FoundationDB#4]
This code intermittently works (only once in about 5 minutes). I am running Centos 7 and PHP 7.3
```
$foundationClient = new \Foundation\Client();
$database = $foundationClient
    ->connection('/etc/foundationdb/fdb.cluster')
    ->database('DB');
$database->set('test', 'testing123');
echo $database->get('test');
```

The error when it is not working is

`Fatal error: Uncaught Foundation\Exception: API version may be set only once in /usr/local/lsws/domain.com/html/test.php:12 Stack trace: #0 /usr/local/lsws/domain.com/html/test.php(12): Foundation\Client->connection('/etc/foundation...') #1 {main} Next Foundation\Exception: Network can be configured only once in /usr/local/lsws/domain.com/html/test.php:12 Stack trace: #0 /usr/local/lsws/domain.com/html/test.php(12): Foundation\Client->connection('/etc/foundation...') #1 {main} thrown in /usr/local/lsws/domain.com/html/test.php on line 12`

My fdbcli status is

```
fdb> status

Using cluster file `/etc/foundationdb/fdb.cluster'.

Configuration:
  Redundancy mode        - double
  Storage engine         - memory-2
  Coordinators           - 3

Cluster:
  FoundationDB processes - 3
  Zones                  - 3
  Machines               - 3
  Memory availability    - 0.6 GB per process on machine with least available
                           >>>>> (WARNING: 4.0 GB recommended) <<<<<
  Fault Tolerance        - 1 machine
  Server time            - 04/03/20 03:12:21

Data:
  Replication health     - Healthy
  Moving data            - 0.000 GB
  Sum of key-value sizes - 0 MB
  Disk space used        - 337 MB

Operating space:
  Storage server         - 1.0 GB free on most full server
  Log server             - 7.2 GB free on most full server

Workload:
  Read rate              - 18 Hz
  Write rate             - 0 Hz
  Transactions started   - 8 Hz
  Transactions committed - 0 Hz
  Conflict rate          - 0 Hz

Backup and DR:
  Running backups        - 0
  Running DRs            - 0

Client time: 04/03/20 03:12:21
fdb> 
```
My local IP is 10.148.0.7
My fdb.cluster is
rsVDreX2:6tIeK5BqiLi4cwjrFgUqUHKpMBCgLvDc@10.148.0.10:4500,10.148.0.12:4500,10.148.0.13:4500

**Comment by viest** [comment]
Hi @chikoi 

Could you please provide a complete piece of code that will help me fix this.

**Comment by chikoi** [comment]
Hi @viest this is my complete test.php file

```
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$foundationClient = new \Foundation\Client();
$database = $foundationClient
    ->connection('/etc/foundationdb/fdb.cluster')
    ->database('DB');
$database->set('test', 'testing123');
echo $database->get('test');
?>
```

**Comment by chikoi** [comment]
I think it will be fixed if we prevent setting api version and network again if these have already been set but currently, I am not sure how to code this.

**Comment by viest** [comment]
Your operating environment FPM or Command Line?

**Comment by chikoi** [comment]
I am not sure but I use OpenLiteSpeed web server which uses their own LSPHP as its PHP API.

**Comment by chikoi** [comment]
It works with Apache + CGI wrapper
but not with FCGid and PHP-FPM mode in Apache and Nginx.

**Comment by viest** [comment]
Hello @chikoi , sorry for the delayed repair;

I reproduced the problem by calling a loop, please confirm whether it is possible.

Thank you!
